micronaut:
  application:
    name: bookMyTickets
  server:
    port: ${PORT:9000}
    context-path: /api
  http:
    client:
      read-timeout: 60
  security:
    enabled: false
    intercept-url-map:
      - pattern: /**/*
        http-method: POST
        access:
          - isAuthenticated()
      - pattern: /**/*
        http-method: GET
        access:
          - isAuthenticated()
      - pattern: /**/*
        http-method: PUT
        access:
          - isAuthenticated()
      - pattern: /**/*
        access:
          - isAuthenticated()
    token:
      jwt:
        okta-auth-configuration:
          is-dev-env: true
          trusted-clients: [ ]
          auth-servers:
            default: default

datasources:
  default:
    url: ${JDBC_DATABASE_URL:`jdbc:postgresql://localhost:5433/bmt_db`}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME:`postgres`}
    password: ${JDBC_DATABASE_PASSWORD:``}

liquibase:
  datasources:
    default:
      change-log: 'classpath:liquibase-changelog.xml'
